name: Test
on:
  push:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Rust
        run: cargo build
      - name: Install Yarn
        run: npm install --global yarn
      - name: Install frontend deps 
        run: yarn --cwd frontend install
      - name: Build frontend
        run: yarn --cwd frontend run build
      - name: Run tests
        run: cargo test
